import Navbar from '@components/Navbar'
import '@styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Food Recipe',
  description: 'Generated by Jecy Jehu',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-full h-full max-w-[380px] sm:max-w-[650px] md:max-w-[1100px] m-auto bg-milk ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
